"""add requester to punch

Revision ID: 1078b35bd003
Revises: 9085a4e89e22
Create Date: 2026-06-22 22:20:42.199460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1078b35bd003'
down_revision = '9085a4e89e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('punch', schema=None) as batch_op:
        batch_op.drop_column('requester')

    # ### end Alembic commands ###
