"""add soft delete columns

Revision ID: 9085a4e89e22
Revises: 
Create Date: 2026-06-10 18:06:28.412705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9085a4e89e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['archived_by_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['archived_by_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['archived_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_by_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_by_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'employee'::character varying"))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_by_id')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_active')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
