"""Add forgot password hashed fields

Revision ID: b263fc4f42d5
Revises: 1078b35bd003
Create Date: 2026-06-25 15:35:35.391008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b263fc4f42d5'
down_revision = '1078b35bd003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('reset_password_expires_at')
        batch_op.drop_column('reset_password_token_hash')
    # ### end Alembic commands ###
